name: TAI_Framework # name of the environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel # required for jupyter notebook in VS Code
  - dvc # Install dvc for managing data and experiments
  - dvclive # Install dvclive for live metrics
  - langchain
  - nbdev
#   - pip  # if you need more packages installed from pip 
  - pip:
    - ipywidgets
    - transformers 
    - llama-index
    - python-dotenv
    - torch
    - torchvision
    - torchaudio 
