name: TAI_Framework # name of the environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel  # required for jupyter notebook in VS Code
  - dvc        # Install dvc for managing data and experiments
  - dvclive    # Install dvclive for live metrics
  - nbdev      # Install nbdev for developing libraries in Jupyter Notebooks
  - langchain
 
#   - pip  # if you need more packages installed from pip 
  - pip:
    - ipywidgets
    - llama-index
    - python-dotenv
    - huggingface_hub 
    - torch
    - torchvision
    - torchaudio
    - huggingface_hub # huggingface_hub
    - transformers    # Install transformers for loading models from Hugging Face
    - datasets        # Install datasets for loading datasets from Hugging Face
